---
# Copyright 2016, Walmart Stores, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: watcher_init_common.yml
  vars:
    program_name: "{{ watcher_api_program_name }}"
    service_name: "{{ watcher_service_name }}"
    system_user: "{{ watcher_system_user_name }}"
    system_group: "{{ watcher_system_group_name }}"
    service_home: "{{ watcher_system_user_home }}"
  when: inventory_hostname in groups['watcher_api']

- include: watcher_init_common.yml
  vars:
    program_name: "{{ watcher_decision_engine_program_name }}"
    service_name: "{{ watcher_service_name }}"
    system_user: "{{ watcher_system_user_name }}"
    system_group: "{{ watcher_system_group_name }}"
    service_home: "{{ watcher_system_user_home }}"
  when: inventory_hostname in groups['watcher_decision_engine']

- include: watcher_init_common.yml
  vars:
    program_name: "{{ watcher_applier_program_name }}"
    service_name: "{{ watcher_service_name }}"
    system_user: "{{ watcher_system_user_name }}"
    system_group: "{{ watcher_system_group_name }}"
    service_home: "{{ watcher_system_user_home }}"
  when: inventory_hostname in groups['watcher_applier']
