---
# Copyright 2016, Walmart Stores, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Place the init script
  template:
    src: "watcher-upstart-init.j2"
    dest: "/etc/init/{{ program_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  register: upstart_init
  notify:
    - Restart watcher services

- name: Reload init scripts
  command: initctl reload-configuration
  when: upstart_init  is changed
  notify:
    - Restart watcher services

- name: Load service
  service:
    name: "{{ program_name }}"
    enabled: "yes"
  notify:
    - Restart watcher services
